In [4]:
import numpy as np

In [ ]:
# Basic Array creation

In [3]:


arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [5]:
a = [1,2,3,4, "hello"]
a

[1, 2, 3, 4, 'hello']

In [6]:
np.array(a)

array(['1', '2', '3', '4', 'hello'], dtype='<U21')

In [7]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [19]:
arr = np.zeros(6)
arr

array([0., 0., 0., 0., 0., 0.])

In [18]:
matrix = np.zeros((4,8))
matrix

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr = np.ones(6)
arr

array([1., 1., 1., 1., 1., 1.])

In [23]:
matrix = np.ones((6,6))
matrix

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [28]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [29]:
# Random Generation function

In [31]:
np.random.rand(10)

array([0.05145964, 0.84627262, 0.25697431, 0.7178743 , 0.15251467,
       0.67917911, 0.27453159, 0.49506119, 0.45778488, 0.00761824])

In [39]:
np.random.randn(10)

array([-0.19859586, -0.48184367, -0.28970796,  0.15056058,  0.91599474,
        0.19544086,  0.65965258,  1.77007737,  0.19470886,  0.73479879])

In [43]:
np.random.randint(10,20,10)

array([14, 12, 18, 16, 17, 14, 13, 15, 12, 12], dtype=int32)

In [44]:
# Array Attributes

In [45]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr.shape

(3, 3)

In [47]:
arr.size

9

In [48]:
arr.dtype

dtype('int64')

In [49]:
# Array method

In [50]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
print(arr.min())

1


In [56]:
arr.max()

np.int64(9)

In [57]:
arr.sum()


np.int64(45)

In [58]:
# column wise additiion
np.sum(arr, axis = 0)

array([12, 15, 18])

In [59]:
# Row wise addition
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [60]:
arr.mean()

np.float64(5.0)

In [61]:
arr.std()

np.float64(2.581988897471611)

In [62]:
arr.argmax()

np.int64(8)

In [63]:
arr.argmin()

np.int64(0)

In [64]:
#Reshaping and Resizing

In [5]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [7]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])