In [4]:
import numpy as np

In [3]:
# NUMPY INDEXING AND SLICING OF VECTORS
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
print(arr[9])

20


In [7]:
arr[1:5]

array([12, 13, 14, 15])

In [8]:
arr[:5]

array([11, 12, 13, 14, 15])

In [9]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
arr[3::2]

array([14, 16, 18, 20])

In [12]:
# NUMPY INDEXING AND SLICING OF MATRIX

In [14]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [15]:
arr[0]

array([1, 2, 3, 4, 5])

In [16]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [17]:
arr[0,0]

np.int64(1)

In [22]:
arr[0:2, 1:3]

array([[2, 3],
       [7, 8]])

In [23]:
arr[3:6, 3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [24]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [25]:
# BOOLEAN INDEXING

In [26]:
bool_index = arr %2 ==0
bool_index 

array([[False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [13]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [14]:
bool_index = arr%2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [15]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])