In [2]:
import numpy as np

In [5]:
#Arithmetic Operations
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

In [6]:
a+b

array([ 7,  9, 11, 13, 15])

In [7]:
a-b

array([-5, -5, -5, -5, -5])

In [8]:
a*b

array([ 6, 14, 24, 36, 50])

In [9]:
a/b

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [10]:
a//b

array([0, 0, 0, 0, 0])

In [11]:
a**b

array([      1,     128,    6561,  262144, 9765625])

In [14]:
# Broadcasting
l = [10,20,30,40]
arr = np.array(l)

In [16]:
arr + 10

array([20, 30, 40, 50])

In [18]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [19]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [24]:
#Deep and Shallow copy
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
slice = a[:5]
slice = slice*10
a

array([100, 200, 300, 400, 500,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [28]:
b = a.copy()

In [37]:
b = b*10
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [45]:
# Matrix Operations

A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

In [46]:
A

array([[1, 2],
       [3, 4]])

In [47]:
B

array([[5, 6],
       [7, 8]])

In [50]:
#Multiplications

# A @ B
# OR
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [61]:
# Transpose

# a.transpose()
# OR
A.T

array([[1, 3],
       [2, 4]])

In [65]:
# Advance Array Manipulation

# Stacking Array
a = np.arange(1,5)
b = np.arange(5,9)


array([5, 6, 7, 8])

In [66]:
#Vertical
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [67]:
#Horizontal
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [68]:
#Column Stack
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])